#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-BDB
Version  : 1.92
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/BDB-1.92.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/BDB-1.92.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-BDB-lib = %{version}-%{release}
Requires: perl-BDB-license = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : db-dev
BuildRequires : perl(common::sense)

%description
NAME
BDB - Asynchronous Berkeley DB access
SYNOPSIS
use BDB;
my $env = db_env_create;

%package dev
Summary: dev components for the perl-BDB package.
Group: Development
Requires: perl-BDB-lib = %{version}-%{release}
Provides: perl-BDB-devel = %{version}-%{release}
Requires: perl-BDB = %{version}-%{release}

%description dev
dev components for the perl-BDB package.


%package lib
Summary: lib components for the perl-BDB package.
Group: Libraries
Requires: perl-BDB-license = %{version}-%{release}

%description lib
lib components for the perl-BDB package.


%package license
Summary: license components for the perl-BDB package.
Group: Default

%description license
license components for the perl-BDB package.


%prep
%setup -q -n BDB-1.92

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-BDB
cp COPYING %{buildroot}/usr/share/package-licenses/perl-BDB/COPYING
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/BDB.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/BDB.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/auto/BDB/BDB.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-BDB/COPYING
